USE avocado;

-- 한글 깨짐 처리
ALTER DATABASEado DEFAULT CHARACTER SET utf8 COLLATE UTF8_GENERAL_CI;
ALTER TABLE member CONVERT TO CHARSET UTF8;

CREATE TABLE member(
  id VARCHAR(16) NOT NULL,
  pw VARCHAR(330) NOT NULL,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  tel VARCHAR(13),
  resdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (id));
  
SELECT * FROM member;